// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Multi_Page_Burgett.Models;

namespace Multi_Page_Burgett.Migrations
{
    [DbContext(typeof(ContactsContext))]
    [Migration("20210206231447_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Multi_Page_Burgett.Models.Contacts", b =>
                {
                    b.Property<int>("ContactsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactsId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactsId = 1,
                            Address = "123 Main Street, Anytown USA",
                            Name = "Ben Gates",
                            Note = "I met Ben while he was looking for a treasure map on the back of the Declaration of Independance.",
                            Phone = "123-456-7891"
                        },
                        new
                        {
                            ContactsId = 2,
                            Address = "Bag End, Bagshot Row, Hobbbiton, Shire ",
                            Name = "Frodo Baggins",
                            Note = "I met Frodo when he joined a fellowship to destrow a powerful ring",
                            Phone = "None"
                        },
                        new
                        {
                            ContactsId = 3,
                            Address = "111 Myhouse Road, Des Moines Ia.",
                            Name = "Angie Burgett",
                            Note = "Angie is my wife, I met her 22 years ago at a local coffee shop. She is truly my better half.",
                            Phone = "515-555-5555"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
