// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Multi_Page_Burgett.Models;

namespace Multi_Page_Burgett.Migrations
{
    [DbContext(typeof(ContactsContext))]
    partial class ContactsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Multi_Page_Burgett.Models.Contacts", b =>
                {
                    b.Property<int>("ContactsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactsId");

                    b.HasIndex("DesignationId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactsId = 1,
                            Address = "123 Main Street, Anytown USA",
                            DesignationId = "Mr.",
                            Name = "Ben Gates",
                            Note = "I met Ben while he was looking for a treasure map on the back of the Declaration of Independance.",
                            Phone = "123-456-7891"
                        },
                        new
                        {
                            ContactsId = 2,
                            Address = "Bag End, Bagshot Row, Hobbbiton, Shire ",
                            DesignationId = "Hobbit",
                            Name = "Frodo Baggins",
                            Note = "I met Frodo when he joined a fellowship to destroy a powerful ring",
                            Phone = "None"
                        },
                        new
                        {
                            ContactsId = 3,
                            Address = "111 Myhouse Road, Des Moines Ia.",
                            DesignationId = "Mrs.",
                            Name = "Angie Burgett",
                            Note = "Angie is my wife, I met her 22 years ago at a local coffee shop. She is truly my better half.",
                            Phone = "515-555-5555"
                        });
                });

            modelBuilder.Entity("Multi_Page_Burgett.Models.Designation", b =>
                {
                    b.Property<string>("DesignationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DesignationId");

                    b.ToTable("Designations");

                    b.HasData(
                        new
                        {
                            DesignationId = "Mr.",
                            Name = "Mister"
                        },
                        new
                        {
                            DesignationId = "Ms.",
                            Name = "Miss"
                        },
                        new
                        {
                            DesignationId = "Mrs.",
                            Name = "Misses"
                        },
                        new
                        {
                            DesignationId = "Hobbit",
                            Name = "Hobbit"
                        },
                        new
                        {
                            DesignationId = "Other",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Multi_Page_Burgett.Models.Contacts", b =>
                {
                    b.HasOne("Multi_Page_Burgett.Models.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Designation");
                });
#pragma warning restore 612, 618
        }
    }
}
